### ISSUE TITLE
reg pyttsx

### ISSUE THREAD

**Issue by SatyaPrakashDwibedi** [SatyaPrakashDwibedi/File_Reader#1]
mind it:
if your pyttsx throws error like this:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\speech.py", line 55, in <module>
    from win32com.client import constants as _constants
  File "C:\Python27\lib\site-packages\win32com\client__init__.py", line 11, in
<module>
    import gencache
  File "C:\Python27\lib\site-packages\win32com\client\gencache.py", line 662, in
 <module>
    **init**()
  File "C:\Python27\lib\site-packages\win32com\client\gencache.py", line 56, in
**init**
    _LoadDicts()
  File "C:\Python27\lib\site-packages\win32com\client\gencache.py", line 109, in
 _LoadDicts
    version = p.load()
EOFError

then search for dicts.dat file and delete it

**Comment by magicbyjim** [comment]
Thank you for the easy fix... I had even uninstalled everything and was still getting the error. Found the file in my user folder on Win10: ...\AppData\Local\Temp\gen_py\3.7\
